In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import LabelEncoder, StandardScaler
import torch.nn as nn
import torch
from torch.utils.data import DataLoader,  TensorDataset
import numpy as np
from tqdm.notebook import tqdm

In [2]:
df = pd.read_csv("dataset.csv")
df

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0               3068          0.002400        0.1700                   16.12   
1               3042          0.000500        0.1542                   16.60   
2               2600          0.000300        0.1020                   18.70   
3               2800          0.000200        0.1600                   16.65   
4               1939          0.000138        0.1030                   20.06   
..               ...               ...           ...                     ...   
235            38940     374830.000000     1356.0000                   -9.93   
236            30839     834042.000000     1194.0000                  -10.63   
237             8829     537493.000000     1423.0000                  -10.73   
238             9235     404940.000000     1112.0000                  -11.23   
239            37882     294903.000000     1783.0000                   -7.80   

     Star type Star color Spectral Class  
0            0        Red              M  
1            0        Red              M  
2            0        Red              M  
3            0        Red              M  
4            0        Red              M  
..         ...        ...            ...  
235          5       Blue              O  
236          5       Blue              O  
237          5      White              A  
238          5      White              A  
239          5       Blue              O  

[240 rows x 7 columns]

In [8]:
def one(x):
    return x + 1

def twenty(x):
    return x + 20

df['Luminosity(L/Lo)'] = df['Luminosity(L/Lo)'].apply(one)
df['Luminosity(L/Lo)'] = df['Luminosity(L/Lo)'].apply(np.log)
df['Absolute magnitude(Mv)'] = df['Absolute magnitude(Mv)'].apply(twenty)

In [9]:
df1 = pd.get_dummies(df["Spectral Class"], dtype = float)
df2 = pd.get_dummies(df["Star color"], dtype = float)
frames = [df, df1, df2]
frame = pd.concat(frames, axis=1, join="inner")
new_df  = frame.drop(["Spectral Class", "Star color"], axis=1)
new_df[:6]

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002397        0.1700                   36.12   
1             3042          0.000500        0.1542                   36.60   
2             2600          0.000300        0.1020                   38.70   
3             2800          0.000200        0.1600                   36.65   
4             1939          0.000138        0.1030                   40.06   
5             2840          0.000650        0.1100                   36.98   

   Star type    A    B    F    G    K  ...  Pale yellow orange  Red  White  \
0          0  0.0  0.0  0.0  0.0  0.0  ...                 0.0  1.0    0.0   
1          0  0.0  0.0  0.0  0.0  0.0  ...                 0.0  1.0    0.0   
2          0  0.0  0.0  0.0  0.0  0.0  ...                 0.0  1.0    0.0   
3          0  0.0  0.0  0.0  0.0  0.0  ...                 0.0  1.0    0.0   
4          0  0.0  0.0  0.0  0.0  0.0  ...                 0.0  1.0    0.0   
5          0  0.0  0.0  0.0  0.0  0.0  ...                 0.0  1.0    0.0   

   White-Yellow  Whitish  Yellowish  Yellowish White  white  yellow-white  \
0           0.0      0.0        0.0              0.0    0.0           0.0   
1           0.0      0.0        0.0              0.0    0.0           0.0   
2           0.0      0.0        0.0              0.0    0.0           0.0   
3           0.0      0.0        0.0              0.0    0.0           0.0   
4           0.0      0.0        0.0              0.0    0.0           0.0   
5           0.0      0.0        0.0              0.0    0.0           0.0   

   yellowish  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
5        0.0  

[6 rows x 31 columns]

In [51]:
array = torch.tensor(new_df.values)
# array = torch.nn.functional.normalize(torch_tensor)
x = torch.cat((array[:,:4], array[:,5:]), axis = 1)
y = array[: , 4]
# x_train, x_test, y_train, y_test = train_test_split(x, y,
#                                                     test_size=0.2, 
#                                                     random_state= 0)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)
 
# Разделение данных
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=30)
 


In [53]:
y_train


tensor([2., 1., 2., 0., 0., 2., 1., 3., 4., 1., 2., 2., 3., 1., 3., 3., 1., 4.,
        1., 2., 1., 5., 0., 4., 5., 4., 3., 1., 0., 0., 0., 0., 1., 1., 5., 0.,
        3., 1., 0., 5., 4., 0., 3., 2., 4., 1., 5., 4., 0., 0., 3., 3., 1., 3.,
        0., 5., 2., 0., 3., 3., 5., 1., 2., 2., 0., 2., 5., 1., 3., 5., 5., 3.,
        0., 4., 5., 0., 0., 2., 1., 4., 1., 2., 3., 1., 3., 0., 3., 5., 5., 0.,
        2., 3., 4., 2., 1., 3., 2., 4., 2., 3., 1., 5., 4., 5., 5., 4., 1., 3.,
        1., 0., 2., 3., 0., 2., 0., 3., 0., 1., 2., 4., 3., 4., 5., 4., 3., 1.,
        1., 3., 4., 0., 4., 3., 4., 2., 4., 4., 5., 0., 2., 1., 3., 1., 5., 5.,
        3., 1., 4., 0., 1., 3., 0., 5., 3., 5., 4., 5., 1., 5., 1., 1., 3., 0.,
        4., 4., 2., 0., 1., 2., 2., 4., 5., 4., 1., 4., 0., 5., 5., 0., 5., 0.,
        4., 1., 5., 2., 5., 1., 3., 2., 4., 5., 4., 3.], dtype=torch.float64)

In [95]:
x_train0 = torch.tensor(x_train, dtype=torch.float32)
# y_train0 = torch.tensor(y_train, dtype=torch.long)
y_train0 = y_train.clone().detach()
y_train0 = y_train0.to(torch.long)
x_test0 = torch.tensor(x_test, dtype=torch.float32)
y_test0 = y_test.clone().detach()
y_test0 = y_test0.to(torch.long)
# y_test0 = torch.tensor(y_test.clone().detach(), dtype=torch.long)

# x_train=x_train.squeeze(1)
# y_train=y_train.squeeze(1)
# x_test=x_test.squeeze(1)
# y_test=y_test.squeeze(1)

In [96]:
y_test0

tensor([4, 5, 0, 0, 5, 5, 5, 0, 5, 3, 4, 2, 1, 0, 3, 4, 1, 0, 5, 4, 2, 4, 2, 2,
        5, 3, 2, 2, 1, 3, 2, 0, 3, 0, 5, 4, 4, 4, 3, 2, 1, 2, 2, 2, 5, 2, 2, 4])

In [97]:
test_dataset[0]

(tensor([ 1.4826,  1.3093, -0.3375, -0.9716, -0.2932, -0.4869, -0.2761, -0.0647,
         -0.1601, -0.9276,  2.2361,  1.8340, -0.0647, -0.2085, -0.1125, -0.0647,
         -0.0647, -0.3486, -0.0917, -0.0647, -0.0647, -0.9354, -0.1733, -0.0647,
         -0.0917, -0.0647, -0.1125, -0.1125, -0.1857, -0.0917]),
 tensor(4))

In [101]:
batch_size = 64
train_dataset = TensorDataset(x_train0, y_train0)
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = TensorDataset(x_test0, y_test0)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

In [12]:
# new_df_train = new_df.sample(n=192)
# new_df_test = new_df.sample(n=48)

# torch_tensor_train = torch.tensor(new_df_train.values)
# torch_tensor_test= torch.tensor(new_df_test.values)

# train_set = torch.nn.functional.normalize(torch_tensor_train)
# test_set = torch.nn.functional.normalize(torch_tensor_test)

In [28]:
# batch_size = 3
# number_of_labels = 6

# train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=0)
# test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=True, num_workers=0)

# classes = ('0', '1', '2', '3', '4', '5')

In [86]:
class Network(torch.nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        # 1 слой, принимающий сигнал
        self.fc1=torch.nn.Linear(30, 200)
        # функция сигмоиды для первого слоя
        self.act1=torch.nn.Sigmoid()
        # 2 слой, принимающий сигнал
        self.fc2 = torch.nn.Linear(200, 200)
        # функция сигмоиды для второго слоя
        self.act2 = torch.nn.Sigmoid()
        # 3 функция активации для выходного слоя
        self.fc3=torch.nn.Linear(200, 6)
    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.fc2(x)
        x = self.act2(x)
        x = self.fc3(x)
        return x

In [87]:
our_network = Network() #если слоев > 1?
our_network 

Network(
  (fc1): Linear(in_features=30, out_features=200, bias=True)
  (act1): Sigmoid()
  (fc2): Linear(in_features=200, out_features=200, bias=True)
  (act2): Sigmoid()
  (fc3): Linear(in_features=200, out_features=6, bias=True)
)

In [88]:
optimizer = torch.optim.Adam(our_network.parameters(), 0.01)
criterion = nn.CrossEntropyLoss()

In [108]:
for epoch in range(500):
    our_network.train()
    for x_batch, y_batch in train_loader:
        optimizer.zero_grad()
        outputs = our_network(x_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
 
    our_network.eval()
    with torch.no_grad():
        val_outputs =our_network(x_test0)
        val_loss = criterion(val_outputs, y_test0)
#         if val_loss < min_val_loss:
#             min_val_loss = val_loss
#             patience_counter = 0
#         else:
#             patience_counter += 1
 
#         if patience_counter >= early_stopping_patience:
#             print(f"Stopped early at epoch {epoch}")
#             break

our_network.eval()
with torch.no_grad():
    outputs = our_network(x_test0)
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y_test0).sum().item() / len(y_test0)
    print(f'Accuracy: {accuracy}')


Accuracy: 1.0
